import Head from 'next/head';
import MainCarousel from '../components/shared/carousel/Carousel';
import Products from '../components/shared/productList/Products';
import { GetStaticProps } from 'next';
import { Axios } from '../utils/axios';
import { PRODUCT_ENDPOINT } from '../enums/endpoint';
import Banner from '../components/shared/banner/Banner';
import CardType1 from '../components/shared/cartType1';
import SectionCart from '../components/shared/sectionCart';
import { Button, Col, Row, ConfigProvider } from 'antd';

export default function Home() {
  return (
    <>
      <Head>
        <title>Binh Ho Service</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="section">
        <MainCarousel />
      </section>
      <section className="section">
        <Banner />
      </section>

      <section className="section">
        <SectionCart />
      </section>
      <ConfigProvider
        theme={{
          token: {
            colorPrimary: '#00b96b',
          },
        }}
      >
        <Button type="primary">BINH HO</Button>
      </ConfigProvider>
    </>
  );
}
