import Head from 'next/head';
import MainCarousel from '../components/shared/carousel/Carousel';
import Banner from '../components/shared/banner/Banner';
import SectionCart from '../components/shared/sectionCart';
import SectionCart2 from '@/components/shared/sectionCart2';
import { ToastContainer } from 'react-toastify';

export default function Home() {
  return (
    <>
      <Head>
        <title>Binh Ho Service</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="section">
        <MainCarousel />
      </section>
      <section className="section">
        <Banner />
      </section>

      <section className="section">
        <SectionCart />
      </section>

      <section className="section">
        <SectionCart2 />
      </section>
    </>
  );
}
